### ISSUE TITLE
feat(Editor): 增加在 ShowSubmit = true 时主动触发 OnValueChanged 回调的方法

### ISSUE THREAD

**Issue by AiYuZhen** [BootstrapBlazor/BootstrapBlazor.Extensions#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

我在发送消息时，想通过对话框的【发送】按钮提交编辑内容，这样用户只需要点出一次按钮就能完成，不用点击两次，又能减少网络占用。
![image](https://github.com/user-attachments/assets/8778350f-90ff-44e5-a203-df396e4c37e6)

### Describe the solution you'd like

1、增加一个方法可以通过代码主动触发 `OnValueChanged` 回调；
2、增加支持返回值的 `DoMethodAsync` 类似方法；

**Comment by ArgoZhang** [comment]
@AiYuZhen 目前设计上不支持哦。富文本框右上角的那个按钮设计上就是让人点才触发 `OnValueChanged` 的。等我有空重新设计一下。增加一个代码可以触发那个按钮的机制。估计明天吧

**Comment by AiYuZhen** [comment]
嗯嗯，好嘞。

**Comment by ArgoZhang** [comment]
@AiYuZhen 提供示例，方便我测试。功能我看了代码已经提供了

**Comment by ArgoZhang** [comment]
@AiYuZhen 增加实例方法 `GetCode`

```
var content = await Editor.GetCode();
```

即可获得当前编辑框内容，点击发送按钮前调用这个方法即可

**Comment by AiYuZhen** [comment]
> @AiYuZhen 提供示例，方便我测试。功能我看了代码已经提供了
已根据 `GetCode` 方法实现预期功能，多谢张佬！
[EidtorTest.zip](https://github.com/user-attachments/files/18073094/EidtorTest.zip)
